version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001" # Starts the server with console enabled
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - nessie-db:/var/lib/postgresql/data

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    depends_on:
      - postgres
    environment:
      NESSIE_VERSION_STORE_TYPE: JDBC
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres_123
    ports:
      - "19120:19120"

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - minio
      - nessie
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog

  spark:
    image: apache/spark:3.5.1
    container_name: spark
    depends_on:
      - minio
      - nessie
    environment:
      SPARK_MODE: client
    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/opt/data
      - ./ivy-cache:/home/spark/.ivy2
    command: sleep infinity

volumes:
  minio-data:
  nessie-db: